/**
 * Error ID constants for structured error tracking and monitoring (e.g., Sentry).
 *
 * Usage:
 * ```typescript
 * import { ERROR_IDS } from '../constants/errorIds.js'
 * throw new AppError("Account not found", 404, ERROR_IDS.TXN_ACCOUNT_NOT_FOUND)
 * ```
 *
 * Naming convention:
 * - Prefix by domain (TXN = Transaction, AUTH = Authentication, etc.)
 * - Use SCREAMING_SNAKE_CASE
 * - Be specific but concise
 */
export const ERROR_IDS = {
  // Transaction errors
  TXN_ACCOUNT_NOT_FOUND: "TXN_ACCOUNT_NOT_FOUND",
  TXN_NOT_FOUND: "TXN_NOT_FOUND",
  TXN_VERSION_CONFLICT: "TXN_VERSION_CONFLICT",
  TXN_CATEGORY_NOT_FOUND: "TXN_CATEGORY_NOT_FOUND",
  TXN_VENDOR_NOT_FOUND: "TXN_VENDOR_NOT_FOUND",
  TXN_DESTINATION_REQUIRED: "TXN_DESTINATION_REQUIRED",
  TXN_DESTINATION_SAME_AS_SOURCE: "TXN_DESTINATION_SAME_AS_SOURCE",
  TXN_DESTINATION_NOT_FOUND: "TXN_DESTINATION_NOT_FOUND",
  TXN_DESTINATION_INVALID_TYPE: "TXN_DESTINATION_INVALID_TYPE",

  // Account errors
  ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
  ACCOUNT_INSUFFICIENT_BALANCE: "ACCOUNT_INSUFFICIENT_BALANCE",

  // Organization errors
  ORG_NOT_FOUND: "ORG_NOT_FOUND",
  ORG_UNAUTHORIZED: "ORG_UNAUTHORIZED",
  ORG_MEMBER_NOT_FOUND: "ORG_MEMBER_NOT_FOUND",

  // Authentication errors
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",

  // Vendor errors
  VENDOR_NOT_FOUND: "VENDOR_NOT_FOUND",
  VENDOR_INACTIVE: "VENDOR_INACTIVE",

  // Category errors
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  CATEGORY_IN_USE: "CATEGORY_IN_USE",

  // Validation errors
  VALIDATION_FAILED: "VALIDATION_FAILED",
  VALIDATION_SPLITS_MISMATCH: "VALIDATION_SPLITS_MISMATCH",

  // Export errors
  EXPORT_INVALID_DATE_RANGE: "EXPORT_INVALID_DATE_RANGE",
  EXPORT_INVALID_DATE_FORMAT: "EXPORT_INVALID_DATE_FORMAT",
  EXPORT_GENERATION_FAILED: "EXPORT_GENERATION_FAILED",
  EXPORT_TIMEOUT: "EXPORT_TIMEOUT",
  EXPORT_TOO_LARGE: "EXPORT_TOO_LARGE",
  EXPORT_ACCOUNT_NOT_FOUND: "EXPORT_ACCOUNT_NOT_FOUND",

  // System errors
  DATABASE_ERROR: "DATABASE_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorId = (typeof ERROR_IDS)[keyof typeof ERROR_IDS];
